# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e42bb6ae7076d04e0fd2b55c8b474f289c4050bf59c668af8f58027026b8d1658894fdab88c54a00ffde3ea2fde5807840e025a8a00b0c6d531f69eb8be47ef2

test:
  secret_key_base: 6f443862c82c28767248d6953f29bbf55e1313cc9765948b5bc53c6a54e89cb807649172b33ecdaae57b4ae578d0197b420ccd7a03c5264226e0e9e208de0a7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
